import time #pour les pauses
print("-----------------------------------------")
print("|Liste des choses a faire pour le projet|")
print("|            Plains Of Wyn              |")
print("-----------------------------------------")
time.sleep(1)
print("1) Player class")
time.sleep(1)
print("2) Loading and saving system w/ pickle")
time.sleep(1)
print("3) Dice function")
time.sleep(1)
print("4) Map and position system with an array and dictionnaries + youtube vid from Btong")
time.sleep(1)
print("5) Reusable command system (class and functions)")
time.sleep(1)
print("6) Move command #pour bouger ")
time.sleep(1)
print("7) Examine command #sert a examnier un truc, la pièce ou autre ")
time.sleep(1)
print("8) Use command #pour utiliser des objets  ")
time.sleep(1)
print("9) More locations and functions for each map? NPCs? Storing a function inside a map dict to link it with a command call?")
time.sleep(1)
print("10) Talk command #pour parler a des NPCs ")
time.sleep(1)
print("11) Player Inventory with a dict and functions for adding checking displaying and adding easily")
time.sleep(1)
print("12) Item system")
time.sleep(1)
print("13) Loot/lootbag generator (class and function)")
time.sleep(1)
print("14) Combat system")
time.sleep(1)
print("15) Attack command #pour utilier son épée ou autre objet permettant d'attaquer (possédant une fonction hit ou dans le Genre)")
time.sleep(1)
print("16) Equip command #pour equiper des items equippables (chaque item contiendrait une variable equippable )")
time.sleep(1)
print("17) Ennemies with inheritance(class and functions, __init__, self etc)")
time.sleep(1)
print("18) Shop")
time.sleep(1)
print("19) Gather system")
time.sleep(1)
print("20) Crafting system")
time.sleep(1)
print("21) Leveling system")
time.sleep(1)
print("22) Chat: /say /tell command # ne sert pas trop en solo, mais sert a chatter et mp en online")
time.sleep(1)
print("23) Online mode with socket.py (petit mode PvP avec elo et matchmaking puis rendre de plus en plus le jeu online)")
time.sleep(1)
print("24) Dungeons")
time.sleep(1)
print("25) Pets/familiars")
time.sleep(1)
print("26) PvE/PvP content!")
